### ISSUE TITLE
Invalid syntax in finetune.py

### ISSUE THREAD

**Issue by Charmelink** [jordiclive/ControlPrefixes#7]
Hi,
I am trying to run 
python3 read_yaml.py configs/DART.yaml

This gives: 

  File "finetune.py", line 84
    self.dataset_kwargs: dict = dict(
____________________^
SyntaxError: invalid syntax

I am on Python 3.6.9

**Comment by jordiclive** [comment]
Can you try python >=3.7

**Comment by Charmelink** [comment]
First of all thanks for your responses! I am excited to try this project. 
Apologies but I am still having a lot of issues. 
My python version was indeed the issue before. 
python > 3.7 does not seem to work, but 3.7 gets a little further. I still run into the following traceback, though.

Traceback (most recent call last):
  File "finetune.py", line 932, in <module>
    model = main(args)
  File "finetune.py", line 902, in main
    logger=logger,
  File "/workspace/ControlPrefixes/src/datatotext/lightning_base.py", line 634, in generic_train
    trainer.fit(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self.call_setup_hook(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1066, in call_setup_hook
    model.setup(stage_name)
  File "/workspace/ControlPrefixes/src/datatotext/lightning_base.py", line 286, in setup
    "train", self.hparams.train_batch_size, shuffle=True
  File "finetune.py", line 610, in get_dataloader
    dataset = self.get_dataset(type_path)
  File "finetune.py", line 603, in get_dataset
    **self.dataset_kwargs,
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'PrefixModule' object has no attribute 'dataset_kwargs'

This is on Python 3.7.13 and the rest of the dependencies are as specified in the setup / requirements of the project. 
I am going to try it on an early version of 3.7, but if you have any other ideas please let me know. 
Thanks again!

**Comment by jordiclive** [comment]
hmm. Ok, I've made it a package and show it can work on colab with python 3.7 [here](https://colab.research.google.com/drive/1pYVWPnvoQTGsF64_UOj7qYIAeh0OAMMO).  You have to enable GPU runtime first.

Takes a while to install as I'm using a forked Transformers and haven't streamlined all the dependencies.

**Comment by Charmelink** [comment]
This worked! I noticed the set up is different than the readme. That change solved my issue. 

Cheers!
